version: '3'

services:
  nginx:
     build: ./nginx/
     container_name: nginx-maxco 
     ports:
       - "80:80"
       - "443:443"
     volumes:
       - ./www:/var/www/html
       - ./nginx/log:/var/log/nginx
     networks:
        webnet:


  php:
    build: ./php/
    container_name: php-maxco
    volumes:
       - ./www:/var/www/html
    expose:
       - "9000"
    networks:
        webnet:

  mariadb:
    image: mariadb
    container_name: mariadb-maxco
    # restart: always
    volumes:
      - ./mariadb:/var/lib/mysql

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: wordpress
    expose:
      - "3306"
    networks:
        webnet:

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      # restart: always
      depends_on:
      - mariadb
      ports:
       - 8183:80
      environment:
        MYSQL_USERNAME: root
        MYSQL_ROOT_PASSWORD: root 
        PMA_HOST: mariadb
        PMA_ARBITRARY: 1
      networks:
        webnet:
                
networks:
  webnet:
